<?php
require_once __DIR__."/../api/connection.php";

try {
    $bd = getConnection();
     $ENTIDADES = "CREATE TABLE `ENTIDADES`
     (
         `ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
         `EMAIL` VARCHAR(50) NOT NULL UNIQUE,
         `PASSWORD` VARCHAR(100) NOT NULL,
         `NUM_DOCUMENTO` VARCHAR(11) UNIQUE,
         `TIPO_DOCUMENTO` CHAR(3),
         `RAZON_SOCIAL` VARCHAR(50),
         `TIPO` VARCHAR(10),
         `DIRECCION` VARCHAR(200),
         `NOMBRE` VARCHAR(50),
         `IMG_URL` VARCHAR(250),
         `CELULAR` VARCHAR(9),
         `TARJETA` CHAR(16)
    );" ;

    $PRODUCTOS ="CREATE TABLE `PRODUCTOS`
     (
         `ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
         `NOMBRE` VARCHAR(50),
         `DESCRIPCION` TEXT,
         `PRECIO` DECIMAL(10,2),
         `ULTIMO_PRECIO` DECIMAL(10,2),
         `IMG_URL` VARCHAR(250),
         `CATEGORIA` VARCHAR(15),
         `BADGE` VARCHAR(200),
         `GRUPO` VARCHAR(10),
         `STOCK` INT,
         `COD_ENTIDAD_PROVEEDOR` INT REFERENCES ENTIDADES(ID)
    );" ;

    $VENTA ="CREATE TABLE `VENTA`
     (
         `ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
         `TIPO_COMPROBANTE` VARCHAR(10),
         `COD_ENTIDAD_CLIENTE` INT REFERENCES ENTIDADES(ID),
         `ESTADO` VARCHAR(10) NOT NULL, /* CART, PENDIENTE, ENVIADO, DESPACHADO*/
         `TS` TIMESTAMP
    );" ;

    $VENTA_DETALLE ="CREATE TABLE `VENTA_DETALLE`
     (
         `ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
         `COD_VENTA` INT REFERENCES VENTA(ID),
         `COD_PRODUCTO` INT REFERENCES PRODUCTOS(ID),
         `STOCK` INT,
         `MONTO_UNIT` DECIMAL(10,2),
         `CANTIDAD` INT
    );" ;

    $bd->exec($ENTIDADES.$PRODUCTOS.$VENTA.$VENTA_DETALLE);
    echo "correcto!";
} catch(PDOException $e) {
    echo $e->getMessage();
}